language: ruby
rvm:
  - 2.0.0
  - 2.1.1
  - 2.3.3
services: mongodb
before_install:
  - gem update bundler
script:
  - rake
after_success:
  - CODECLIMATE_REPO_TOKEN=787a2f89b15c637323c7340d65ec17e898ac44480706b4b4122ea040c2a88f1d bundle exec codeclimate-test-reporter
